import dev.ichinomiya.ninebotenhance.core.NotificationTimeline;
import dev.ichinomiya.ninebotenhance.core.NotificationDeduplicator;
import dev.ichinomiya.ninebotenhance.core.MusicPlayback;
import dev.ichinomiya.ninebotenhance.core.SidebarLayout;
import dev.ichinomiya.ninebotenhance.core.WidgetSettings;
import dev.ichinomiya.ninebotenhance.core.WidgetCondition;
import java.io.File;
import java.util.List;
import org.w3c.dom.*;

final class NotificationTests {
    static void run() throws Exception {
        CoreTests.check(MusicPlayback.hasTrack(2)&&MusicPlayback.hasTrack(3)&&MusicPlayback.hasTrack(6)&&MusicPlayback.hasTrack(8),"paused, playing and loading sessions retain music details");
        CoreTests.check(!MusicPlayback.hasTrack(0)&&!MusicPlayback.hasTrack(1)&&!MusicPlayback.hasTrack(7)&&!MusicPlayback.hasTrack(-1)&&!MusicPlayback.hasTrack(12),"absent, stopped, failed and unknown sessions hide music details");
        CoreTests.check(MusicPlayback.position(10000,180000,3,1,1000,5000)==14000,"playing position uses monotonic elapsed time");
        CoreTests.check(MusicPlayback.position(10000,180000,2,1,1000,5000)==10000,"paused music progress does not advance");
        CoreTests.check(MusicPlayback.position(179000,180000,3,1,1000,5000)==180000,"progress cannot run beyond duration");
        CoreTests.check(MusicPlayback.position(1000,180000,5,-2,1000,5000)==0,"rewind cannot move before zero");
        CoreTests.check(MusicPlayback.position(-1,180000,3,1,1000,5000)==-1,"unknown music position remains unknown");
        CoreTests.check(MusicPlayback.position(10000,180000,3,Float.NaN,1000,5000)==10000,"malformed speed cannot corrupt progress");
        CoreTests.check(MusicPlayback.time(65000).equals("1:05")&&MusicPlayback.time(-1).equals("--:--"),"time format supports unknown playback state");
        CoreTests.check(NotificationTimeline.requireWidth(180)==180&&NotificationTimeline.requireWidth(600)==600,"notification width boundaries accepted");
        CoreTests.rejects(()->NotificationTimeline.requireWidth(179),"unreadable notification width rejected");CoreTests.rejects(()->NotificationTimeline.requireWidth(601),"oversized notification width rejected");
        NotificationTimeline<String> q=new NotificationTimeline<>();
        q.add("1","first",15000,0);q.add("2","second",15000,500);q.add("3","third",15000,1000);
        CoreTests.check(q.entries(1000).size()==3,"three notifications fit while phone state remains visible");
        q.add("4","fourth",15000,1500);
        CoreTests.check(q.entries(1500).size()==3&&q.entries(1500).get(2).exitAt==1500,"fourth retires the oldest before inserting");
        CoreTests.check(q.entries(1739).size()==3&&q.entries(1739).get(0).key.equals("3"),"exiting notification still occupies its slot");
        CoreTests.check(q.entries(1740).size()==3&&q.entries(1740).get(0).key.equals("4"),"fourth slides in after oldest exits");
        CoreTests.check(q.entries(1740).get(0).enter(1740)==0,"new arrivals start outside the right edge");
        CoreTests.close(q.entries(1740).get(0).enter(2180),1,"arrival finishes at 440 ms");
        q.clear();q.add("same","a",1000,0);q.add("same","b",1000,500);
        CoreTests.check(q.entries(500).size()==2&&q.entries(500).get(0).data.equals("b")&&q.entries(500).get(1).data.equals("a"),"new posts reusing one notification key retain both immutable cards");
        CoreTests.check(q.entries(760).get(1).exitAt==760&&q.entries(760).get(0).exitAt<0,"each post has its own display lifetime");
        CoreTests.check(q.entries(1000).size()==1&&q.entries(1000).get(0).data.equals("b"),"old post expires without removing the later same-key post");
        CoreTests.check(q.empty(1500),"second post receives its full one-second lifetime including exit animation");
        q.add("same","1",15000,2000);q.add("same","2",15000,2500);q.add("same","3",15000,3000);q.add("same","4",15000,3500);
        CoreTests.check(q.entries(3739).size()==3&&q.entries(3739).get(0).data.equals("3"),"same-app burst still waits for oldest card to leave");
        CoreTests.check(q.entries(3740).size()==3&&q.entries(3740).get(0).data.equals("4"),"four same-key posts obey three-card capacity");
        q.add("same","5",15000,3800);q.remove("same",3900);
        NotificationTimeline<String> limited=new NotificationTimeline<>();
        CoreTests.check(NotificationTimeline.clampLimit(0)==1&&NotificationTimeline.clampLimit(9)==5&&limited.limit()==3,"visible limit clamps to one through five with a default of three");
        CoreTests.check(limited.setLimit(1,0)&&!limited.setLimit(1,0),"changing the limit reports whether it changed");
        limited.add("a","a",15000,0);limited.add("b","b",15000,100);
        CoreTests.check(limited.entries(100).size()==1&&limited.entries(100).get(0).exitAt==100,"a limit of one retires the visible card for the next one");
        CoreTests.check(limited.entries(340).size()==1&&limited.entries(340).get(0).key.equals("b"),"the next card enters once the old one has left");
        limited.clear();limited.setLimit(5,1000);for(int i=0;i<6;i++)limited.add("m"+i,"m",15000,1000+i);
        CoreTests.check(limited.entries(1005).size()==5&&limited.entries(1005).get(4).exitAt>=0,"a limit of five shows five cards and retires the oldest for a sixth");
        CoreTests.check(limited.setLimit(2,2000)&&limited.entries(2000).size()==4&&limited.entries(2000).get(1).exitAt<0&&limited.entries(2000).get(2).exitAt==2000&&limited.entries(2000).get(3).exitAt==2000,"lowering the limit retires every card beyond it and keeps the pending one waiting");
        CoreTests.check(limited.entries(2999).size()==2&&limited.entries(2999).get(0).key.equals("m4")&&limited.entries(2999).get(1).exitAt==2999,"once the retired cards leave, the next oldest makes room for the waiting card");
        CoreTests.check(limited.entries(3500).size()==2&&limited.entries(3500).get(0).key.equals("m5")&&limited.entries(3500).get(1).key.equals("m4"),"the waiting card enters under the new limit");
        CoreTests.check(q.empty(4140),"removing the source notification clears all matching visible and pending cards");
        NotificationDeduplicator posts=new NotificationDeduplicator();
        CoreTests.check(posts.accept("same",100,"title","message"),"first notification callback is accepted");
        CoreTests.check(!posts.accept("same",100,"title","message"),"redelivery of the exact same post is ignored");
        CoreTests.check(posts.accept("same",101,"title","message"),"same text with a new event timestamp is a new notification");
        CoreTests.check(posts.accept("same",101,"title","new message"),"different content is independent even at the same millisecond");
        CoreTests.check(posts.accept("other",101,"title","new message"),"different source keys are independent");
        CoreTests.check(posts.remove("same")&&posts.accept("same",101,"title","new message"),"cancelled notification key can be reused");
        posts.clear();CoreTests.check(posts.accept("same",101,"title","new message"),"session reset clears duplicate tracking");
        for(int i=0;i<129;i++)posts.accept("bounded"+i,200,"title","message");
        CoreTests.check(posts.accept("bounded0",200,"title","message"),"duplicate cache is bounded to 128 source keys");
        var a=new NotificationDeduplicator.Message(1000,"Alice","first");
        var b=new NotificationDeduplicator.Message(2000,"Alice","second");
        var c=new NotificationDeduplicator.Message(3000,"Bob","third");
        posts.clear();
        CoreTests.check(posts.acceptMessages("chatA",List.of(a)).equals(List.of(a)),"first chat message is displayed");
        CoreTests.check(posts.acceptMessages("chatB",List.of(c)).equals(List.of(c)),"another conversation is independent");
        CoreTests.check(posts.acceptMessages("chatA",List.of(a)).isEmpty(),"refresh of old chat during another chat arrival is suppressed");
        CoreTests.check(posts.acceptMessages("chatA",List.of(a,b)).equals(List.of(b)),"conversation snapshot emits only added message");
        CoreTests.check(posts.acceptMessages("chatA",List.of(a,b)).isEmpty(),"same conversation snapshot cannot replay its history");
        CoreTests.check(posts.acceptMessages("chatA",List.of(a)).isEmpty()&&posts.acceptMessages("chatA",List.of(a,b)).isEmpty(),"temporarily shortened snapshots do not forget seen messages");
        var d=new NotificationDeduplicator.Message(4000,"Alice","fourth");
        CoreTests.check(posts.acceptMessages("chatA",List.of(a,b,c,d)).equals(List.of(c,d)),"multiple new messages in one update are separately accepted");
        CoreTests.check(posts.acceptMessages("history",List.of(a,b,c)).equals(List.of(c)),"first snapshot remembers unread history without replaying it");
        CoreTests.check(posts.acceptMessages("history",List.of(a,b,c)).isEmpty(),"initial unread history stays suppressed");
        var same=new NotificationDeduplicator.Message(5000,"Alice","same text");
        CoreTests.check(posts.acceptMessages("duplicates",List.of(same)).size()==1,"identical-content sequence starts with one message");
        CoreTests.check(posts.acceptMessages("duplicates",List.of(same,same)).size()==1,"two identical messages in the same timestamp second remain distinct by occurrence");
        CoreTests.check(posts.acceptMessages("duplicates",List.of(same,same)).isEmpty(),"same-second duplicate snapshot does not re-emit either occurrence");
        CoreTests.check(posts.acceptMessages("duplicates",List.of(same)).isEmpty()&&posts.acceptMessages("duplicates",List.of(same,same,same)).size()==1,"shrinking a snapshot cannot lower seen occurrence counts");
        CoreTests.check(posts.acceptMessages("history",List.of(new NotificationDeduplicator.Message(500,"old sender","old unseen"),c)).isEmpty(),"older history inserted in a later snapshot is not a new notification");
        q.clear();
        q.add("long","text",60000,1000);CoreTests.check(!q.empty(60999)&&q.empty(61000),"sixty-second duration boundary is exact");
        q.add("remove","text",15000,70000);q.remove("remove",71000);CoreTests.check(q.empty(71240),"removed phone notification leaves dashboard");
        for(int i=0;i<100;i++){q.add("storm"+i,"data",15000,80000+i);CoreTests.check(q.entries(80000+i).size()<=3,"burst never exceeds capacity");}
        q.clear();CoreTests.check(q.empty(200000),"session stop clears pending and visible notifications");
        for(int i=0;i<8;i++)q.add("queued"+i,"data",15000,201000);
        CoreTests.check(q.empty(250000),"suspended consumer drops expired pending notifications instead of replaying them");
        q.add("hidden","data",15000,210000);CoreTests.check(q.empty(300000),"suspended consumer cannot show expired cards");
        CoreTests.check(NotificationTimeline.duration(5)==5000&&NotificationTimeline.duration(30)==30000,"notification settings accept both slider endpoints");
        CoreTests.rejects(()->NotificationTimeline.duration(4),"settings below five seconds rejected");CoreTests.rejects(()->NotificationTimeline.duration(31),"settings above thirty seconds rejected");
        CoreTests.check(NotificationTimeline.clampSeconds(1)==5&&NotificationTimeline.clampSeconds(60)==30&&NotificationTimeline.clampSeconds(15)==15,"legacy settings clamp into the new slider range without changing the default");
        sidebar();motion();conditions();
        var factory=javax.xml.parsers.DocumentBuilderFactory.newInstance();factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);
        Document manifest=factory.newDocumentBuilder().parse(new File("app/src/main/AndroidManifest.xml"));
        Element listener=find(manifest,"service",".notification.MirrorNotificationListener"),settings=find(manifest,"activity",".ui.NotificationSettingsActivity");
        CoreTests.check(listener!=null&&"android.permission.BIND_NOTIFICATION_LISTENER_SERVICE".equals(listener.getAttribute("android:permission")),"system notification listener is protected by the signature binding permission");
        CoreTests.check(settings!=null&&"false".equals(settings.getAttribute("android:exported"))&&settings.getElementsByTagName("intent-filter").getLength()==0,"permission UI is private and has no public or launcher entry");
        Element picker=find(manifest,"activity",".ui.LaunchAppPickerActivity");
        CoreTests.check(picker!=null&&"false".equals(picker.getAttribute("android:exported"))&&picker.getElementsByTagName("intent-filter").getLength()==0,"launch-app consent and selection stay in a private module activity");
        CoreTests.check(find(manifest,"uses-permission","android.permission.READ_PHONE_STATE")!=null,"SIM signal permission is declared");
        CoreTests.check(find(manifest,"uses-permission","android.permission.QUERY_ALL_PACKAGES")!=null,"notification app allowlist includes apps with no launcher");
        CoreTests.check(find(manifest,"uses-permission","android.permission.READ_PHONE_NUMBERS")==null&&find(manifest,"uses-permission","android.permission.READ_CONTACTS")==null,"phone HUD does not request numbers or contacts");
    }
    private static void conditions(){
        var c=WidgetCondition.parse("2,0,5,3,5,30,100,900,40,60,0,100");
        CoreTests.check(c.mode()==WidgetCondition.WHILE&&c.uses(WidgetCondition.SPEED)&&c.uses(WidgetCondition.POWER)&&!c.uses(WidgetCondition.VOLTAGE)&&c.matches(10,500,Float.NaN,Float.NaN,false)&&!c.matches(4,500,0,0,true)&&!c.matches(10,Float.NaN,0,0,true)&&c.matches(10,-500,Float.NaN,Float.NaN,false)&&!c.matches(10,-50,Float.NaN,Float.NaN,false)&&c.encode().equals("2,0,5,3,5,30,100,900,40,60,0,100,12,35,12,35,-20,100,-20,100"),"a while-condition needs every checked value inside its range, compares power by magnitude, and encodes with open tyre ranges");
        var open=new WidgetCondition(WidgetCondition.WHILE,0,5,WidgetCondition.SPEED|WidgetCondition.TYRE_FRONT_PRESSURE,0,160,0,30000,20,90,0,100,12,30,12,35,-20,100,-20,100);
        CoreTests.check(open.matches(new WidgetCondition.Measurements(300,Float.NaN,Float.NaN,Float.NaN,false,2.4f,Float.NaN,Float.NaN,Float.NaN))&&open.matches(new WidgetCondition.Measurements(0,0,0,0,false,3.0f,0,0,0))&&!open.matches(new WidgetCondition.Measurements(300,0,0,0,false,3.2f,0,0,0))&&!open.matches(new WidgetCondition.Measurements(300,0,0,0,false,Float.NaN,0,0,0))&&open.uses(WidgetCondition.TYRE_CHECKS)&&!open.uses(WidgetCondition.TYRE_REAR_TEMP)&&WidgetCondition.parse(open.encode()).equals(open)&&WidgetCondition.parse("2,0,5,3,5,30,100,900,40,60,0,100").frontPressureMax()==35,"bounds at the slider limits are open, tyre checks compare tenths of a bar, and both encodings parse");
        CoreTests.check(WidgetCondition.describe(0,160,0,160,1,"km/h").equals("−∞ ~ +∞")&&WidgetCondition.describe(5,160,0,160,1,"km/h").equals("5 km/h ~ +∞")&&WidgetCondition.describe(0,30,0,160,1,"km/h").equals("−∞ ~ 30 km/h")&&WidgetCondition.describe(15,30,12,35,10,"bar").equals("1.5 ~ 3.0 bar")&&WidgetCondition.describe(12,30,12,35,10,"bar").equals("−∞ ~ 3.0 bar")&&WidgetCondition.MAX_SPEED==160&&WidgetCondition.MAX_POWER==30000&&WidgetCondition.MAX_VOLTAGE==90,"range text shows open ends as infinity and scales tenths");
        CoreTests.check(WidgetSettings.DEFAULT.with(WidgetSettings.TYRES,false).withCondition(WidgetSettings.PHONE,open).readsTyres()&&!WidgetSettings.DEFAULT.with(WidgetSettings.TYRES,false).readsTyres(),"a tyre condition keeps tyres read while the tyre card is off");
        var swapped=new WidgetCondition(WidgetCondition.WHILE,0,99,WidgetCondition.VOLUME|WidgetCondition.PLAYING,0,0,0,0,0,0,80,20);
        CoreTests.check(swapped.volumeMin()==20&&swapped.volumeMax()==80&&swapped.showSeconds()==30&&swapped.voltageMin()==20&&swapped.matches(0,0,0,50,true)&&!swapped.matches(0,0,0,50,false)&&!swapped.matches(0,0,0,10,true),"reversed ranges are swapped, values clamp, and playing must be true when checked");
        var change=WidgetCondition.onChange(WidgetCondition.VOLUME_CHANGE,3);
        CoreTests.check(change.triggered(WidgetCondition.VOLUME_CHANGE)&&!change.triggered(WidgetCondition.TRACK_CHANGE)&&!change.uses(WidgetCondition.VOLUME)&&change.showMs()==3000&&WidgetCondition.parse("garbage").equals(WidgetCondition.ALWAYS_SHOWN)&&WidgetCondition.parse(null).equals(WidgetCondition.ALWAYS_SHOWN)&&!WidgetCondition.ALWAYS_SHOWN.triggered(WidgetCondition.VOLUME_CHANGE),"change conditions only react to their triggers; malformed text means always shown");
        CoreTests.check(WidgetSettings.DEFAULT.condition(WidgetSettings.MUSIC).equals(WidgetCondition.onChange(WidgetCondition.TRACK_CHANGE|WidgetCondition.PLAYBACK_CHANGE,5))&&WidgetSettings.DEFAULT.with(WidgetSettings.MUSIC_AUTO_HIDE,false).condition(WidgetSettings.MUSIC).equals(WidgetCondition.ALWAYS_SHOWN)&&WidgetSettings.DEFAULT.condition(WidgetSettings.PHONE).equals(WidgetCondition.ALWAYS_SHOWN)&&WidgetSettings.DEFAULT.conditions().isEmpty(),"music keeps its auto-hide as the default condition; other widgets are always shown");
        var gated=WidgetSettings.DEFAULT.with(WidgetSettings.HILL_HOLD_DODGE,false).withCondition(WidgetSettings.PHONE,c);
        CoreTests.check(gated.condition(WidgetSettings.PHONE).equals(c)&&gated.readsSpeed()&&gated.readsPower()&&!gated.readsVoltage()==false&&!gated.with(WidgetSettings.PHONE,false).readsSpeed()&&!WidgetSettings.DEFAULT.with(WidgetSettings.HILL_HOLD_DODGE,false).readsSpeed()&&gated.withCondition(WidgetSettings.PHONE,WidgetCondition.ALWAYS_SHOWN).conditions().isEmpty()&&gated.withMask(WidgetSettings.PHONE).condition(WidgetSettings.PHONE).equals(c),"conditions make their measurements read while the widget is on, survive mask edits, and an always-shown condition is dropped");
        var reordered=WidgetSettings.DEFAULT.withOrder(List.of(WidgetSettings.MUSIC,WidgetSettings.NOTIFICATIONS,99,WidgetSettings.MUSIC));
        CoreTests.check(reordered.order().equals(List.of(WidgetSettings.MUSIC,WidgetSettings.NOTIFICATIONS,WidgetSettings.PHONE,WidgetSettings.TYRES,WidgetSettings.VOLTAGE,WidgetSettings.SPEED,WidgetSettings.POWER,WidgetSettings.LAMP,WidgetSettings.BMS,WidgetSettings.COLUMN_DIVIDER))&&reordered.encodeOrder().equals("4,16,1,2,128,32768,65536,524288,1048576,0")&&WidgetSettings.parseOrder("4,16,1,2,128,32768,65536,524288").equals(reordered.order())&&WidgetSettings.parseOrder("x").equals(WidgetSettings.DEFAULT_ORDER)&&WidgetSettings.DEFAULT.order().equals(WidgetSettings.DEFAULT_ORDER)&&reordered.withMask(0).order().equals(reordered.order()),"orders drop unknown and repeated entries, append missing cards in default order, round-trip through text and survive mask edits");
        var split=WidgetSettings.DEFAULT.withOrder(List.of(WidgetSettings.NOTIFICATIONS,WidgetSettings.PHONE,WidgetSettings.MUSIC,WidgetSettings.COLUMN_DIVIDER,WidgetSettings.TYRES,WidgetSettings.VOLTAGE));
        CoreTests.check(split.rightOrder().equals(List.of(WidgetSettings.NOTIFICATIONS,WidgetSettings.PHONE,WidgetSettings.MUSIC,WidgetSettings.SPEED,WidgetSettings.POWER,WidgetSettings.LAMP,WidgetSettings.BMS))&&split.leftOrder().equals(List.of(WidgetSettings.TYRES,WidgetSettings.VOLTAGE))&&split.encodeOrder().equals("16,1,4,32768,65536,524288,1048576,0,2,128")&&WidgetSettings.DEFAULT.withOrder(WidgetSettings.parseOrder("0,16,2")).rightOrder().get(0)==WidgetSettings.NOTIFICATIONS&&WidgetSettings.DEFAULT.withOrder(WidgetSettings.parseOrder("0,16,2")).leftOrder().equals(List.of(WidgetSettings.TYRES))&&WidgetSettings.DEFAULT.withOrder(WidgetSettings.parseOrder("0,2,0,128")).leftOrder().equals(List.of(WidgetSettings.TYRES,WidgetSettings.VOLTAGE)),"the divider splits the order into right and left columns; missing cards join the right column, notifications always stay right and extra dividers collapse");
        var twoColumns=SidebarLayout.arrange(split,true,true,0);
        CoreTests.check(twoColumns.phone().bottom()==468&&twoColumns.music().bottom()==434&&twoColumns.tyres().right()==633&&twoColumns.tyres().left()==443&&twoColumns.tyres().bottom()==468&&twoColumns.voltage().right()==633&&twoColumns.voltage().bottom()+6==twoColumns.tyres().top()&&SidebarLayout.LEFT_COLUMN_RIGHT==633,"left-column cards stack from the bottom edge just left of the right column");
        var twoLifted=SidebarLayout.arrange(split,true,true,66);
        CoreTests.check(twoLifted.tyres().bottom()==402&&twoLifted.phone().bottom()==402&&twoLifted.tyres().right()==633&&SidebarLayout.arrange(split.withOrder(List.of(WidgetSettings.PHONE,WidgetSettings.NOTIFICATIONS,WidgetSettings.MUSIC,WidgetSettings.COLUMN_DIVIDER,WidgetSettings.TYRES)),true,true,66).tyres().bottom()==368,"notifications lift the left column above their block wherever it sits");
        var twoDodge=SidebarLayout.arrange(split,true,true,0,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(twoDodge.phone().right()==568&&twoDodge.music().right()==568&&twoDodge.tyres().right()==633&&twoDodge.tyres().bottom()==344&&twoDodge.voltage().bottom()==310&&SidebarLayout.arrange(split.with(WidgetSettings.PHONE,false),true,false,0,new SidebarLayout.Sizes(190,190,190,190),true).tyres().bottom()==366,"during hill hold the left column rises above the cards pushed out of the right column and above the toast");
        var tall=WidgetSettings.DEFAULT.with(WidgetSettings.SPEED,true).with(WidgetSettings.POWER,true).withOrder(List.of(WidgetSettings.NOTIFICATIONS,WidgetSettings.PHONE,WidgetSettings.MUSIC,WidgetSettings.POWER,WidgetSettings.COLUMN_DIVIDER,WidgetSettings.VOLTAGE,WidgetSettings.SPEED,WidgetSettings.TYRES));
        var between=SidebarLayout.arrange(tall,true,true,66);
        CoreTests.check(between.power().right()==633&&between.power().bottom()==222&&between.speed().bottom()==312&&between.tyres().bottom()==132&&between.voltage().bottom()==402&&between.music().bottom()==368&&SidebarLayout.arrange(tall,true,true,0).power().right()==838&&SidebarLayout.arrange(tall,true,true,0).power().top()==260,"a card pushed out of the right column slots into the left column by height, between the cards above and below it, and returns once the column is short enough");
        var musicFirst=SidebarLayout.arrange(reordered,true,true,0);
        CoreTests.check(musicFirst.music().bottom()==468&&musicFirst.phone().bottom()+6==musicFirst.music().top()&&musicFirst.tyres().bottom()+6==musicFirst.phone().top(),"the column follows the configured order");
        var phoneBelow=SidebarLayout.arrange(WidgetSettings.DEFAULT.withOrder(List.of(WidgetSettings.PHONE,WidgetSettings.NOTIFICATIONS,WidgetSettings.MUSIC)),true,true,66);
        CoreTests.check(phoneBelow.phone().bottom()==468&&phoneBelow.notificationBottom()==434&&phoneBelow.music().bottom()==368&&SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,66).notificationBottom()==468&&SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,66).phone().bottom()==402&&SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0).notificationBottom()==468,"a card ordered below the notifications keeps its place while the notification block and the cards above it move up");
        var phoneBelowDodge=SidebarLayout.arrange(WidgetSettings.DEFAULT.withOrder(List.of(WidgetSettings.PHONE,WidgetSettings.NOTIFICATIONS,WidgetSettings.MUSIC)),true,true,66,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(phoneBelowDodge.phone().right()==568&&phoneBelowDodge.notificationDodged()&&phoneBelowDodge.notificationBottom()==434&&phoneBelowDodge.music().right()==838&&phoneBelowDodge.music().bottom()==366,"during hill hold a covered notification block slides left with the covered cards and the rest restack on the toast");
        var highNotifications=SidebarLayout.arrange(WidgetSettings.DEFAULT.withOrder(List.of(WidgetSettings.PHONE,WidgetSettings.MUSIC,WidgetSettings.TYRES,WidgetSettings.VOLTAGE,WidgetSettings.NOTIFICATIONS)),true,true,66,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(!highNotifications.notificationDodged()&&highNotifications.notificationBottom()==242&&highNotifications.tyres().bottom()==366&&highNotifications.voltage().right()==633&&highNotifications.voltage().bottom()==176&&highNotifications.music().right()==568,"an uncovered notification block restacks with the uncovered cards above the toast");
        CoreTests.check(SidebarLayout.arrange(WidgetSettings.DEFAULT,WidgetSettings.PHONE|WidgetSettings.VOLTAGE,0,new SidebarLayout.Sizes(190,190,190,190),false).music()==null&&SidebarLayout.arrange(WidgetSettings.DEFAULT,WidgetSettings.PHONE|WidgetSettings.VOLTAGE,0,new SidebarLayout.Sizes(190,190,190,190),false).voltage().bottom()==434&&normal().of(WidgetSettings.MUSIC).equals(normal().music())&&normal().of(WidgetSettings.VOLUME)==null,"a visibility mask hides cards whatever their switches say, and boxes can be looked up by flag");
        CoreTests.check(WidgetSettings.MIN_CHART_SECONDS==10&&WidgetSettings.DEFAULT.chart(10).chartSeconds()==10&&WidgetSettings.DEFAULT.chart(9).chartSeconds()==10&&WidgetSettings.DEFAULT.speedChart(15).speedChartSeconds()==15,"chart windows start at ten seconds");
    }
    private static SidebarLayout.Stack normal(){return SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0);}
    private static void sidebar(){
        var normal=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0);
        var hidden=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,false,0);
        CoreTests.check(normal.phone().bottom()==468&&normal.music().bottom()+6==normal.phone().top()&&normal.tyres().bottom()+6==normal.music().top()&&normal.voltage().right()==633&&normal.voltage().bottom()==468,"enabled widgets pack upwards with six-pixel gaps: phone, music, tyres; the chart voltage would reach into the instrument and moves to the left column");
        CoreTests.check(normal.music().height()==84&&normal.voltage().height()==84&&normal.tyres().height()==28&&normal.tyres().top()==316&&normal.voltage().top()==384&&SidebarLayout.INSTRUMENT.bottom()==254,"playing music is 68 high, the chart voltage 84 and the tyre line 28; the moved voltage card starts at the left column bottom");
        CoreTests.check(hidden.music()==null&&hidden.tyres().bottom()+6==hidden.phone().top()&&hidden.voltage().top()==316&&hidden.voltage().right()==838,"hidden music lets the tyre card drop by its height and gap and the voltage card returns to the right column");
        var noChart=SidebarLayout.arrange(WidgetSettings.DEFAULT.with(WidgetSettings.VOLTAGE_CHART,false),true,true,0);
        CoreTests.check(noChart.voltage().height()==28&&noChart.voltage().top()==282&&noChart.voltage().right()==838&&noChart.tyres().top()==normal.tyres().top(),"without the chart the voltage card is a single row on top of the unchanged tyre line");
        CoreTests.check(SidebarLayout.arrange(new WidgetSettings(WidgetSettings.TYRES),true,false,0).tyres()==null&&SidebarLayout.arrange(new WidgetSettings(WidgetSettings.TYRES|WidgetSettings.TYRE_REAR),true,false,0).tyres().bottom()==468,"a tyre card needs at least one wheel and packs against the lower edge on its own");
        var justMusic=SidebarLayout.arrange(new WidgetSettings(WidgetSettings.MUSIC),true,true,0);
        CoreTests.check(justMusic.phone()==null&&justMusic.voltage()==null&&justMusic.tyres()==null&&justMusic.music().bottom()==468,"disabled widgets leave no empty slots");
        var empty=SidebarLayout.arrange(new WidgetSettings(0),true,true,0);
        CoreTests.check(empty.phone()==null&&empty.music()==null&&empty.voltage()==null&&empty.tyres()==null,"all sidebar widgets can be hidden");
        CoreTests.check(new WidgetSettings(~0).mask()==WidgetSettings.ALL,"unknown preference bits are ignored");
        var sized=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0,new SidebarLayout.Sizes(121,57,107,204));
        CoreTests.check(sized.phone().left()==838-121&&sized.music().left()==838-57&&sized.voltage().left()==633-107&&sized.tyres().left()==648&&sized.tyres().right()==838,"every card takes its own width at the shared right edge and no card exceeds the sidebar width");
        CoreTests.check(sized.phone().top()==normal.phone().top()&&sized.music().top()==normal.music().top()&&sized.tyres().top()==normal.tyres().top(),"widths do not change the vertical stacking");
        var dodge=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(dodge.phone().right()==568&&dodge.phone().bottom()==468&&dodge.music().right()==568&&dodge.music().bottom()==434&&dodge.tyres().right()==838&&dodge.tyres().bottom()==366&&dodge.voltage().right()==633&&dodge.voltage().bottom()==344,"cards the toast covers slide left at their own height; the rest restack on the toast top edge, and a restacked card under the instrument joins the left column above the pushed-out cards");
        var dodgeQuiet=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,false,0,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0,new SidebarLayout.Sizes(190,190,190,190),false).equals(normal)&&dodgeQuiet.music()==null&&dodgeQuiet.phone().right()==568&&dodgeQuiet.tyres().right()==568&&dodgeQuiet.tyres().bottom()==434&&dodgeQuiet.voltage().right()==568&&dodgeQuiet.voltage().bottom()==400,"dodge off keeps the normal layout; without music every card reaching into the toast slides left");
        var dodgeLifted=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,66,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(dodgeLifted.phone().right()==568&&dodgeLifted.phone().bottom()==402&&dodgeLifted.music().right()==838&&dodgeLifted.music().bottom()==366&&dodgeLifted.tyres().right()==633&&dodgeLifted.tyres().bottom()==366&&dodgeLifted.voltage().right()==633&&dodgeLifted.voltage().bottom()==332&&SidebarLayout.covered(new SidebarLayout.Box(648,374,838,402))&&!SidebarLayout.covered(dodgeLifted.phone())&&!SidebarLayout.covered(new SidebarLayout.Box(648,300,838,368))&&SidebarLayout.dodgeShift()==-270,"with one notification only the lifted phone card is covered; music restacks on the toast and the cards that would then reach the instrument continue in the left column");
        var metrics=SidebarLayout.arrange(WidgetSettings.DEFAULT.with(WidgetSettings.SPEED,true).with(WidgetSettings.POWER,true),true,true,0);
        CoreTests.check(metrics.speed().bottom()+6==metrics.voltage().top()&&metrics.power().bottom()+6==metrics.speed().top()&&metrics.speed().height()==84&&metrics.power().height()==84&&metrics.power().top()==204&&metrics.voltage().right()==633&&metrics.voltage().bottom()==468&&normal.speed()==null&&normal.power()==null,"speed and power cards stack above the voltage card at the same size and are off by default");
        var metricsDodge=SidebarLayout.arrange(WidgetSettings.DEFAULT.with(WidgetSettings.SPEED,true),true,false,0,new SidebarLayout.Sizes(190,190,190,190),true);
        CoreTests.check(metricsDodge.voltage().right()==568&&metricsDodge.voltage().bottom()==400&&metricsDodge.speed().right()==838&&metricsDodge.speed().bottom()==366&&metricsDodge.tyres().right()==568,"during hill hold a ride card that stays clear of the toast restacks on it while covered cards slide left");
        CoreTests.check(SidebarLayout.arrange(WidgetSettings.DEFAULT.with(WidgetSettings.SPEED,true).with(WidgetSettings.SPEED_CHART,false),true,true,0).speed().height()==28&&normal.shifted(-10).equals(new SidebarLayout.Stack(normal.phone().shifted(-10),normal.music().shifted(-10),normal.voltage().shifted(-10),normal.tyres().shifted(-10),null,null)),"a ride card without its chart is a single row and the lift shifts absent cards as null");
        CoreTests.check(SidebarLayout.HILL_HOLD_TOAST.left()==574&&SidebarLayout.HILL_HOLD_TOAST.top()==372&&SidebarLayout.HILL_HOLD_TOAST.right()==848,"the toast rectangle matches the dashboard measurement");
        var clamped=SidebarLayout.arrange(WidgetSettings.DEFAULT,true,true,0,new SidebarLayout.Sizes(500,0,900,900));
        CoreTests.check(clamped.phone().left()==648&&clamped.music().left()==838-24&&clamped.voltage().left()==443&&clamped.voltage().right()==633&&clamped.tyres().left()==648,"card widths never exceed the sidebar or collapse below the padding, in either column");
        CoreTests.check(normal.shifted(-100).voltage().top()==284&&normal.shifted(-100).phone().bottom()==368&&normal.shifted(0)==normal,"a notification lift shifts every card together");
        CoreTests.check(SidebarLayout.VOLUME.right()<100&&SidebarLayout.VOLUME.bottom()<389&&SidebarLayout.VOLUME.top()>100,"the volume bar sits at the lower left above the dashboard speaker icon");
        CoreTests.check(WidgetSettings.DEFAULT.with(WidgetSettings.TYRE_READ,false).readsTyres()&&WidgetSettings.DEFAULT.with(WidgetSettings.VOLTAGE_READ,false).readsVoltage()&&!WidgetSettings.DEFAULT.with(WidgetSettings.TYRES,false).readsTyres()&&!WidgetSettings.DEFAULT.with(WidgetSettings.VOLTAGE,false).readsVoltage()&&!new WidgetSettings(WidgetSettings.TYRE_READ).readsTyres(),"tyre and voltage reads follow their cards; the old read switches no longer gate them");
        CoreTests.check(!WidgetSettings.DEFAULT.with(WidgetSettings.VOLTAGE_FROM_BMS,true).readsVoltage()&&!WidgetSettings.DEFAULT.with(WidgetSettings.POWER_FROM_BMS,true).with(WidgetSettings.HILL_HOLD_DODGE,false).with(WidgetSettings.POWER,true).readsPower()&&WidgetSettings.DEFAULT.with(WidgetSettings.POWER_FROM_BMS,true).readsPower(),"the BMS source stops the dashboard voltage and power reads, except the power hill hold needs");
        var limits=new WidgetSettings(WidgetSettings.ALL,0,0,0,0);
        CoreTests.check(limits.tyreIntervalSeconds()==5&&limits.voltageIntervalMs()==500&&limits.musicHideSeconds()==3&&limits.chartSeconds()==10&&new WidgetSettings(WidgetSettings.ALL,999,999,999,999).tyreIntervalSeconds()==60&&new WidgetSettings(WidgetSettings.ALL,999,99999,999,999).voltageIntervalMs()==15000&&new WidgetSettings(WidgetSettings.ALL,999,999,999,999).musicHideSeconds()==15&&new WidgetSettings(WidgetSettings.ALL,999,999,999,999).chartSeconds()==60,"intervals, the music hide delay and the chart window clamp to their slider ranges");
        CoreTests.check(WidgetSettings.DEFAULT.tyreIntervalSeconds()==30&&WidgetSettings.DEFAULT.voltageIntervalMs()==1000&&WidgetSettings.DEFAULT.tyreLimitMs()==60000&&WidgetSettings.DEFAULT.voltageLimitMs()==5000&&WidgetSettings.DEFAULT.musicHideMs()==5000&&WidgetSettings.DEFAULT.chartWindowMs()==30000&&WidgetSettings.DEFAULT.chart(45).chartSeconds()==45&&WidgetSettings.DEFAULT.chart(45).musicHideSeconds()==5,"defaults read tyres every 30 s and voltage every second, expiring at two and five intervals, hide music after five seconds and chart the last 30 s");
        CoreTests.check(WidgetSettings.DEFAULT.speedChartSeconds()==30&&WidgetSettings.DEFAULT.powerChartSeconds()==30&&WidgetSettings.DEFAULT.speedChart(45).speedChartSeconds()==45&&WidgetSettings.DEFAULT.speedChart(45).chartSeconds()==30&&WidgetSettings.DEFAULT.speedChart(45).powerChartSeconds()==30&&WidgetSettings.DEFAULT.powerChart(60).powerChartWindowMs()==60000&&WidgetSettings.DEFAULT.powerChart(99).powerChartSeconds()==60&&WidgetSettings.migrate(4,WidgetSettings.ALL,30,1000,5,40,100,0,1000,1000,300,3).speedChartSeconds()==30,"speed and power charts keep their own windows, clamped like the voltage window and defaulted for older preferences");
        CoreTests.check(WidgetSettings.migrate(4,WidgetSettings.ALL,30,1000,5,40,100,0,1000,1000,300,3).holdSeconds()==1&&WidgetSettings.migrate(5,WidgetSettings.ALL,30,1000,5,40,100,0,1000,1000,300,3).holdSeconds()==3&&WidgetSettings.migrate(5,WidgetSettings.ALL,300,1,5,40,100,0,1,1,300,3).tyreIntervalSeconds()==60&&WidgetSettings.migrate(5,WidgetSettings.ALL,300,1,5,40,100,0,1,1,300,3).voltageIntervalMs()==500,"saves before version 5 take the new hill-hold minimum; intervals from older ranges clamp into the new ones");
        CoreTests.check(WidgetSettings.DEFAULT.with(WidgetSettings.TYRE_FRONT,false).showsTyres()&&!WidgetSettings.DEFAULT.with(WidgetSettings.TYRE_FRONT,false).with(WidgetSettings.TYRE_REAR,false).showsTyres()&&WidgetSettings.DEFAULT.intervals(60,2000).tyreLimitMs()==120000&&WidgetSettings.DEFAULT.intervals(60,2000).voltageLimitMs()==10000&&WidgetSettings.DEFAULT.musicHide(9).musicHideSeconds()==9&&WidgetSettings.DEFAULT.musicHide(9).tyreIntervalSeconds()==30,"row, interval and hide updates keep the other settings");
        CoreTests.check(WidgetSettings.migrate(1,WidgetSettings.PHONE|WidgetSettings.TYRES,30,1,5,30).enabled(WidgetSettings.VOLUME)&&WidgetSettings.migrate(1,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.MUSIC_AUTO_HIDE)&&!WidgetSettings.migrate(2,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.VOLUME)&&!WidgetSettings.migrate(1,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.MUSIC),"masks saved before version 2 gain the new switches and keep their existing choices");
        CoreTests.check(WidgetSettings.migrate(2,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.HILL_HOLD_DODGE)&&!WidgetSettings.migrate(3,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.HILL_HOLD_DODGE)&&WidgetSettings.DEFAULT.enabled(WidgetSettings.HILL_HOLD_DODGE),"version 2 masks gain the hill-hold dodge, which is on by default");
        CoreTests.check(WidgetSettings.DEFAULT.holdPowerMin()==100&&WidgetSettings.DEFAULT.holdSpeedMax()==0&&WidgetSettings.DEFAULT.holdSpeedMaxTenths()==0&&WidgetSettings.DEFAULT.hold(0,9).holdPowerMin()==50&&WidgetSettings.DEFAULT.hold(0,9).holdSpeedMax()==3&&WidgetSettings.DEFAULT.hold(150,2).holdSpeedMaxTenths()==20&&WidgetSettings.DEFAULT.hold(150,2).withMask(WidgetSettings.PHONE).holdPowerMin()==150,"hill-hold thresholds default to 100 raw power and 0 km/h, clamp to their sliders and survive mask edits");
        CoreTests.check(!WidgetSettings.DEFAULT.enabled(WidgetSettings.SPEED)&&!WidgetSettings.DEFAULT.enabled(WidgetSettings.POWER)&&WidgetSettings.DEFAULT.enabled(WidgetSettings.SPEED_CHART)&&WidgetSettings.DEFAULT.enabled(WidgetSettings.POWER_CHART)&&WidgetSettings.DEFAULT.readsSpeed()&&WidgetSettings.DEFAULT.readsPower()&&!WidgetSettings.DEFAULT.with(WidgetSettings.HILL_HOLD_DODGE,false).readsSpeed()&&WidgetSettings.DEFAULT.with(WidgetSettings.HILL_HOLD_DODGE,false).with(WidgetSettings.POWER,true).readsPower(),"ride cards are off by default with their charts pre-enabled; speed and power are read for the cards or for hill hold");
        var reads=WidgetSettings.DEFAULT.readIntervals(10,2000,3000,4000);
        CoreTests.check(reads.tyreIntervalSeconds()==10&&reads.voltageIntervalMs()==2000&&reads.speedIntervalMs()==3000&&reads.powerIntervalMs()==4000&&reads.speedLimitMs()==15000&&reads.holdPowerMax()==300&&WidgetSettings.DEFAULT.readIntervals(0,0,0,0).speedIntervalMs()==500&&WidgetSettings.DEFAULT.readIntervals(0,0,0,0).speedLimitMs()==2500&&WidgetSettings.DEFAULT.readIntervals(999,99999,99999,99999).powerIntervalMs()==15000,"read intervals are independent, allow half seconds and clamp to their sliders");
        var range=WidgetSettings.DEFAULT.holdRange(60,250,1,2);
        CoreTests.check(range.holdPowerMin()==60&&range.holdPowerMax()==250&&range.holdSpeedMax()==1&&range.holdSeconds()==2&&range.holdMs()==2000&&WidgetSettings.DEFAULT.holdRange(0,999,9,9).holdPowerMax()==500&&WidgetSettings.DEFAULT.holdRange(0,0,0,0).holdPowerMax()==200&&WidgetSettings.DEFAULT.holdRange(0,0,0,0).holdSeconds()==1&&WidgetSettings.DEFAULT.holdPowerMax()==300&&WidgetSettings.DEFAULT.holdSeconds()==1&&WidgetSettings.DEFAULT.holdMs()==1000,"hill-hold range and duration default to 300 raw power and 1 s and clamp to their sliders");
        CoreTests.check(WidgetSettings.migrate(3,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.SPEED_CHART)&&!WidgetSettings.migrate(3,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.SPEED)&&!WidgetSettings.migrate(4,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.POWER_CHART),"version 3 masks gain the ride chart switches but not the ride cards");
        CoreTests.check(!WidgetSettings.DEFAULT.enabled(WidgetSettings.REGISTER_PROBE)&&new WidgetSettings(WidgetSettings.ALL).enabled(WidgetSettings.REGISTER_PROBE)&&!WidgetSettings.migrate(1,WidgetSettings.PHONE,30,1,5,30).enabled(WidgetSettings.REGISTER_PROBE)&&WidgetSettings.DEFAULT.with(WidgetSettings.REGISTER_PROBE,true).enabled(WidgetSettings.REGISTER_PROBE),"the register probe is opt-in and never switched on by defaults or migration");
    }
    private static void motion(){
        var motion=new dev.ichinomiya.ninebotenhance.core.CardMotion();
        var a=new SidebarLayout.Box(700,400,838,428);var b=new SidebarLayout.Box(650,300,838,368);
        motion.target(a,1000);
        CoreTests.check(motion.box(1000).equals(a)&&motion.alpha(1000)==1&&!motion.animating(1000),"the first target settles immediately without an appearance animation");
        motion.target(b,2000);
        CoreTests.check(motion.animating(2000)&&motion.box(2000).equals(a)&&motion.box(2150).top()<a.top()&&motion.box(2150).top()>b.top()&&motion.box(2150).left()<a.left()&&motion.box(2300).equals(b)&&!motion.animating(2300),"a new target glides position and size over 300 ms");
        motion.target(b,2100);
        CoreTests.check(motion.box(2300).equals(b),"repeating the same target does not restart the motion");
        motion.target(null,3000);
        CoreTests.check(motion.drawn(3000)&&motion.alpha(3000)==1&&motion.alpha(3110)<1&&motion.alpha(3110)>0&&motion.box(3110).top()>b.top()&&motion.alpha(3220)==0&&!motion.drawn(3220),"hiding fades the card out while it sinks, and it is not drawn once transparent");
        motion.target(a,4000);
        CoreTests.check(motion.alpha(4000)==0&&motion.box(4000).top()>a.top()&&motion.alpha(4220)==1&&motion.box(4300).equals(a),"showing again fades the card in as it rises to its place");
        motion.target(null,5000);motion.target(a,5100);
        CoreTests.check(motion.alpha(5100)<1&&motion.alpha(5100)>0&&motion.alpha(5400)==1,"re-showing during a fade-out continues from the current opacity");
    }
    private static Element find(Document d,String tag,String name){NodeList list=d.getElementsByTagName(tag);for(int i=0;i<list.getLength();i++){Element e=(Element)list.item(i);if(name.equals(e.getAttribute("android:name")))return e;}return null;}
}
